# Generated by Django 4.2.4 on 2023-12-27 15:21

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.SmallIntegerField(validators=[question.models.validate_number])),
                ('verification_code', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ismi:")),
                ('email', models.EmailField(max_length=254, unique=True, validators=[question.models.validate_geeks_mail])),
                ('number', models.CharField(max_length=20, verbose_name='Nomerizni kiriting:')),
                ('file', models.FileField(upload_to='yes/', validators=[question.models.validate_file])),
                ('status', models.CharField(choices=[('new', 'new'), ('execution', 'execution'), ('completed', 'completed')], default='new', max_length=9, verbose_name='Status:')),
                ('question', models.TextField(verbose_name='Savol matni:')),
                ('answers', models.FileField(upload_to='yes/', validators=[question.models.validate_file])),
            ],
            options={
                'verbose_name': 'Savollar_',
            },
        ),
    ]
